version: '3'

services:
  frontend:
    build:
      context: ./mantine-template-main
    ports:
      - "5173:5173"
    env_file:
      - ./.env # Use the shared .env file for environment variables
    stdin_open: true
    tty: true
    depends_on:
      - backend  # Ensure backend starts first
    networks:
      - app-network

  backend:
    build:
      context: ./server
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
    env_file:
      - ./.env # Use the same .env file here for backend variables
    environment:
      - FLASK_ENV=development
    stdin_open: true
    tty: true
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
